# Practice

In [60]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
data=load_digits()

In [61]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(data['data'],data['target'],test_size=0.3)

In [62]:
lr=LogisticRegression(max_iter=10000)
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

0.9703703703703703

In [63]:
svm=SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9888888888888889

In [64]:
rf=RandomForestClassifier(n_estimators=40)
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9777777777777777

In [65]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [66]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [67]:
def get_score(model, X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [68]:
get_score(LogisticRegression(max_iter=10000),X_train,X_test,y_train,y_test)

0.9703703703703703

# K-Fold Cross Validation

In [69]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold()

In [70]:
scores_l=[]
scores_svm=[]
scores_rf=[]
for train_index,test_index in folds.split(data['data'],data['target']):
    X_train, X_test, y_train, y_test=data['data'][train_index],data['data'][test_index],data['target'][train_index],data['target'][test_index]
    scores_l.append(get_score(LogisticRegression(max_iter=10000),X_train,X_test,y_train,y_test))
    scores_svm.append(get_score(SVC(),X_train,X_test,y_train,y_test))
    scores_rf.append(get_score(RandomForestClassifier(),X_train,X_test,y_train,y_test))


In [71]:
scores_l

[0.925,
 0.8777777777777778,
 0.9387186629526463,
 0.9331476323119777,
 0.8969359331476323]

In [72]:
scores_rf

[0.9416666666666667,
 0.9194444444444444,
 0.9637883008356546,
 0.9554317548746518,
 0.9303621169916435]

In [73]:
scores_svm

[0.9611111111111111,
 0.9444444444444444,
 0.9832869080779945,
 0.9888579387186629,
 0.9387186629526463]

# K-Fold Cross Validation using sklearn

In [74]:
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier

In [75]:
cross_val_score(LogisticRegression(max_iter=10000),data['data'],data['target'])

array([0.925     , 0.87777778, 0.93871866, 0.93314763, 0.89693593])

In [76]:
cross_val_score(SVC(C=40,kernel='rbf'),data['data'],data['target'])

array([0.98055556, 0.95833333, 0.98328691, 0.98885794, 0.95821727])

In [77]:
cross_val_score(DecisionTreeClassifier(),data['data'],data['target'])

array([0.76388889, 0.70833333, 0.78830084, 0.83286908, 0.81058496])

In [78]:
cross_val_score(RandomForestClassifier(n_estimators=50),data['data'],data['target'])

array([0.91944444, 0.91388889, 0.94986072, 0.97214485, 0.92479109])